### ISSUE TITLE
Software sustainability

### ISSUE THREAD

**Issue by bhigy** [spokenlanguage/platalea#41]
Define actions still required by the software sustainability plan and implement them.
 - [x] Presence of documentation targeting new users, illustrating the software's intended usage
 - [ ] ~Filling the Cll Best Practices Badge Program checklist + post the results (badge in the README)~ --> #93
 - [ ] ~Any part worth contributing back to pytorch?~ --> #92
 - [x] Define a consistent versioning strategy
 - [x] Add a DOI through Zenodo

**Comment by bhigy** [comment]
@cwmeijer and @egpbos, can one of you look into this (in particular the 3rd point)?

**Comment by egpbos** [comment]
Wow, this is the first time I read these [CII criteria](https://bestpractices.coreinfrastructure.org/en/criteria/0), very exhaustive, nice!

Under "Warning flags" it basically says we should use a linter in strict mode. I think this can indeed be very useful. I once did a project with pylint at maximum strict mode. At first it's very annoying, but in the end I was very happy with the result, even though I sometimes disagree with the defaults. Strict mode also notifies you that you should write doc-strings for all functions and modules. This way we would automatically satisfy the documentation criteria.

Of course, we don't want to get into holy formatting wars ;) But I think we are actually already very close in the way we write code. I would say that we just configure pylint to ignore the things we still turn out to disagree on, which is easy enough to do.

Then we can also add a linting check to CI. I would also then activate the linter in my editor, so that it becomes easy to fix some warnings along the way (i.e. while you may be doing something else).

**Comment by bhigy** [comment]
Sounds good to me. It will also force me to finally set the linewidth properly. I still get warnings when the line exceeds 80 characters, while I think we once talked about setting that to 120.

**Comment by bhigy** [comment]
> Wow, this is the first time I read these [CII criteria](https://bestpractices.coreinfrastructure.org/en/criteria/0), very exhaustive, nice!

This comes from the software sustainability plan that the eScience center asked us to fill. :smiley: I didn't know about that either.

**Comment by egpbos** [comment]
Ahaha, right, clearly I wasn't involved in that ;)

**Comment by egpbos** [comment]
Yeah, I personally tend to set it to 120, but I have no issues making it bigger still, or ignoring the rule entirely. There are a lot of rules that are far more useful than this :)

**Comment by bhigy** [comment]
Other point we should discuss I think is the versioning of the code. I would like to add a DOI to the repository through Zenodo, which can automatically archive the different releases of the code. Making such releases on a consistent basis would be good (we have one so far).

**Comment by egpbos** [comment]
With commit 54fc3407621570d62473d5da5f13c4d5b9c61c45, I fixed the LabelEncoder warning (code quality improvement, CII section "Warning flags").

**Comment by egpbos** [comment]
Another warning fix should hopefully come from https://github.com/wandb/client/pull/2129

**Comment by egpbos** [comment]
Wandb PR has been merged, so that's another warning gone after updating to wandb 0.10.30.

**Comment by egpbos** [comment]
All Python warnings from running the experiments are gone now, also #90.

A next logical step would be to "fix" all current linter warnings produced by flake8. After that, we could see what pylint on extreme strictness levels suggests, maybe it has some useful ideas.

**Comment by egpbos** [comment]
Ok, made a PR for a first run of flake8 fixes: #91.

For next steps, we should probably make a list of things we need to do to fulfill the CII criteria. Let's start out just copying it and striking through items we have already. I'll do this in a new issue to keep this one from becoming too long and messy.

In fact, I'll just go ahead and split up everything I think is still unresolved from this thread into separate issues, so we can close this and continue there:

- Contributing back / generalization: #92.
- CII checklist: #93.
- Versioning, DOI and Zenodo: #94.
- Linting: #95.
